### ISSUE TITLE
Question for you: what is the function of default-key and trusted-key in gpg.conf? 

### ISSUE THREAD

**Issue by chapb** [drduh/config#2]
It looks like in the latest commit of the gpg.conf file, it adds several lines which includes your gpg key as a default-key and trusted-key. I just wanted to confirm the function of those two arguments, as there's little documentation online. 

Thanks! Loved the guide.

**Comment by drduh** [comment]
Those options select my key ID as the default identity to try when calling decrypt operations. It's useful in combination with `throw-keyids` since the recipient identity is not included in the ciphertext, forcing gpg to cycle all identities when decrypting. This can be annoying if you have several identities/keys. I'll make a note in the next push, thanks!

**Comment by chapb** [comment]
That makes sense - thanks!
